// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApFcqSz6weiFsNH2o63y515CFgirXSHLM',
    appId: '1:614178011755:web:0828fa6bf39cb1b97acf2e',
    messagingSenderId: '614178011755',
    projectId: 'dishdash-c5193',
    authDomain: 'dishdash-c5193.firebaseapp.com',
    storageBucket: 'dishdash-c5193.appspot.com',
    measurementId: 'G-RV0Q81H91Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGCUgVqfUQQFWkrTYdtyuQmw0VvJVmLbw',
    appId: '1:614178011755:android:19a710840a4baf007acf2e',
    messagingSenderId: '614178011755',
    projectId: 'dishdash-c5193',
    storageBucket: 'dishdash-c5193.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7wZKwrNi1iyPdFO1A4QELVWjHpVZKjiY',
    appId: '1:614178011755:ios:9c68074e294cc1917acf2e',
    messagingSenderId: '614178011755',
    projectId: 'dishdash-c5193',
    storageBucket: 'dishdash-c5193.appspot.com',
    iosClientId: '614178011755-ruc5kpfue200jbujtuhuurfo7l8i6cqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.spooncular',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7wZKwrNi1iyPdFO1A4QELVWjHpVZKjiY',
    appId: '1:614178011755:ios:9c68074e294cc1917acf2e',
    messagingSenderId: '614178011755',
    projectId: 'dishdash-c5193',
    storageBucket: 'dishdash-c5193.appspot.com',
    iosClientId: '614178011755-ruc5kpfue200jbujtuhuurfo7l8i6cqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.spooncular',
  );
}
